/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.banking.banktransfer.dtos;

import com.saburi.root.dtos.ResponseData;
import com.saburi.banking.bankaccount.BankAccount;


public interface BankTransferMini  extends ResponseData{


Integer getId();
BankAccount getFromAccountNo();


}
