/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.banking.banktransfer.dtos;

import jakarta.validation.constraints.NotNull;
import com.saburi.root.enums.BankAccountTypes;
import com.saburi.banking.bankaccount.BankAccount;
import jakarta.validation.constraints.Size;


public class BankTransferRequest{

@NotNull(message =  "The field: From Account Type cannot be null")
private BankAccountTypes fromAccountType;
@NotNull(message =  "The field: From Account No cannot be null")
private BankAccount fromAccountNo;
private String fromCurrencyId;
@NotNull(message =  "The field: To Account Type cannot be null")
private BankAccountTypes toAccountType;
@NotNull(message =  "The field: To Account No cannot be null")
private BankAccount toAccountNo;
@Size(max =  100, message =  "The field: To Currency size cannot be greater than 100")
private String toCurrencyId;
private double exchangeRate;
private double amountTendered;
@NotNull(message ="The field: Amount cannot be null")
private double amount;

public BankTransferRequest(){
}
public  BankTransferRequest(BankAccountTypes fromAccountType,BankAccount fromAccountNo,String fromCurrencyId,BankAccountTypes toAccountType,BankAccount toAccountNo,String toCurrencyId,double exchangeRate,double amountTendered,double amount){
 this.fromAccountType = fromAccountType;
this.fromAccountNo = fromAccountNo;
this.fromCurrencyId = fromCurrencyId;
this.toAccountType = toAccountType;
this.toAccountNo = toAccountNo;
this.toCurrencyId = toCurrencyId;
this.exchangeRate = exchangeRate;
this.amountTendered = amountTendered;
this.amount = amount;

}

public BankAccountTypes getFromAccountType(){
 return fromAccountType;
}
public void setFromAccountType(BankAccountTypes fromAccountType){
this.fromAccountType = fromAccountType;
}public BankAccount getFromAccountNo(){
 return fromAccountNo;
}
public void setFromAccountNo(BankAccount fromAccountNo){
this.fromAccountNo = fromAccountNo;
}public String getFromCurrencyId(){
 return fromCurrencyId;
}
public void setFromCurrencyId(String fromCurrencyId){
this.fromCurrencyId = fromCurrencyId;
}public BankAccountTypes getToAccountType(){
 return toAccountType;
}
public void setToAccountType(BankAccountTypes toAccountType){
this.toAccountType = toAccountType;
}public BankAccount getToAccountNo(){
 return toAccountNo;
}
public void setToAccountNo(BankAccount toAccountNo){
this.toAccountNo = toAccountNo;
}public String getToCurrencyId(){
 return toCurrencyId;
}
public void setToCurrencyId(String toCurrencyId){
this.toCurrencyId = toCurrencyId;
}public double getExchangeRate(){
 return exchangeRate;
}
public void setExchangeRate(double exchangeRate){
this.exchangeRate = exchangeRate;
}public double getAmountTendered(){
 return amountTendered;
}
public void setAmountTendered(double amountTendered){
this.amountTendered = amountTendered;
}public double getAmount(){
 return amount;
}
public void setAmount(double amount){
this.amount = amount;
}


}
