/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.organisation.company.dtos;

import org.springframework.web.multipart.MultipartFile;
import jakarta.validation.constraints.Size;
import com.saburi.organisation.enums.BusinessTypes;
import com.saburi.root.enums.DbTypes;


public class CompanyRequest{

private MultipartFile logo;
@Size(max =  100, message =  "The field: Company Name size cannot be greater than 100")
private String companyName;
private BusinessTypes businessType;
@Size(max =  100, message =  "The field: Address size cannot be greater than 100")
private String address;
@Size(max =  100, message =  "The field: Phone No size cannot be greater than 100")
private String phoneNo;
@Size(max =  100, message =  "The field: Email size cannot be greater than 100")
private String email;
@Size(max =  100, message =  "The field: Website size cannot be greater than 100")
private String website;
@Size(max =  100, message =  "The field: Tag Line size cannot be greater than 100")
private String tagLine;
@Size(max =  100, message =  "The field: Dev Name size cannot be greater than 100")
private String devName;
private DbTypes dbType;
@Size(max =  100, message =  "The field: Db Username size cannot be greater than 100")
private String dbUsername;
@Size(max =  100, message =  "The field: Db Password size cannot be greater than 100")
private String dbPassword;
private int dbPort;
@Size(max =  100, message =  "The field: Db Host size cannot be greater than 100")
private String dbHost;
@Size(max =  50, message =  "The field: Url size cannot be greater than 50")
private String url;

public CompanyRequest(){
}
public  CompanyRequest(MultipartFile logo,String companyName,BusinessTypes businessType,String address,String phoneNo,String email,String website,String tagLine,String devName,DbTypes dbType,String dbUsername,String dbPassword,int dbPort,String dbHost,String url){
 this.logo = logo;
this.companyName = companyName;
this.businessType = businessType;
this.address = address;
this.phoneNo = phoneNo;
this.email = email;
this.website = website;
this.tagLine = tagLine;
this.devName = devName;
this.dbType = dbType;
this.dbUsername = dbUsername;
this.dbPassword = dbPassword;
this.dbPort = dbPort;
this.dbHost = dbHost;
this.url = url;

}

public MultipartFile getLogo(){
 return logo;
}
public void setLogo(MultipartFile logo){
this.logo = logo;
}public String getCompanyName(){
 return companyName;
}
public void setCompanyName(String companyName){
this.companyName = companyName;
}public BusinessTypes getBusinessType(){
 return businessType;
}
public void setBusinessType(BusinessTypes businessType){
this.businessType = businessType;
}public String getAddress(){
 return address;
}
public void setAddress(String address){
this.address = address;
}public String getPhoneNo(){
 return phoneNo;
}
public void setPhoneNo(String phoneNo){
this.phoneNo = phoneNo;
}public String getEmail(){
 return email;
}
public void setEmail(String email){
this.email = email;
}public String getWebsite(){
 return website;
}
public void setWebsite(String website){
this.website = website;
}public String getTagLine(){
 return tagLine;
}
public void setTagLine(String tagLine){
this.tagLine = tagLine;
}public String getDevName(){
 return devName;
}
public void setDevName(String devName){
this.devName = devName;
}public DbTypes getDbType(){
 return dbType;
}
public void setDbType(DbTypes dbType){
this.dbType = dbType;
}public String getDbUsername(){
 return dbUsername;
}
public void setDbUsername(String dbUsername){
this.dbUsername = dbUsername;
}public String getDbPassword(){
 return dbPassword;
}
public void setDbPassword(String dbPassword){
this.dbPassword = dbPassword;
}public int getDbPort(){
 return dbPort;
}
public void setDbPort(int dbPort){
this.dbPort = dbPort;
}public String getDbHost(){
 return dbHost;
}
public void setDbHost(String dbHost){
this.dbHost = dbHost;
}public String getUrl(){
 return url;
}
public void setUrl(String url){
this.url = url;
}


}
