/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.organisation.company.dtos;

import com.saburi.root.dtos.ResponseData;


public interface CompanyMini  extends ResponseData{


String getId();
String getCompanyName();


}
