/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.sales.writeoff.dtos;

import com.saburi.root.dtos.ResponseData;


public interface WriteOffMini  extends ResponseData{


String getId();
String getCustomerId();


}
