/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.customer.engagement;

import com.saburi.root.repositories.PagingAndSortingRepo;
import com.saburi.customer.engagement.dtos.EngagementRequest;
import org.springframework.beans.factory.annotation.Autowired;import org.springframework.stereotype.Service;
import com.saburi.root.services.BaseService;
import com.saburi.root.dtos.ResponseData;
import com.saburi.root.utils.KnownException;
import java.util.List;

@Service
public class EngagementService  extends BaseService<Engagement,EngagementRequest, Long>{




    private static final String ENTITY_CAPTION = "Engagement";
    @Autowired
    private EngagementRepo engagementRepo;
@Override
public String getEntityCaption(){
 return ENTITY_CAPTION;
}
@Override
public PagingAndSortingRepo<Engagement, Long> getRepository(){
 return engagementRepo;
}
@Override
public List<? extends ResponseData> getMiniData(){
 return engagementRepo.findAllBy();
}
@Override
public boolean isValid(Engagement engagement)throws Exception{
 return super.isValid(engagement);
}
@Override
public Engagement instantiate(){
 return new Engagement();
}
@Override
    public Engagement setEntity(Engagement e, EngagementRequest req) throws Exception{
e.setCustomer(req. getCustomer());
e.setEngagementDate(req. getEngagementDate());
e.setEngagementReason(req. getEngagementReason());
e.setEngagementMode(req. getEngagementMode());
e.setDescription(req. getDescription());
e.setAttendingPersonnel(req. getAttendingPersonnel());
e.setStatus(req. getStatus());
e.setNextEngagementDate(req. getNextEngagementDate());
e.setExpectedNextEngagementMode(req. getExpectedNextEngagementMode());
e.setParentEngagement(req. getParentEngagement());
return e;

}


}
