/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.customer.engagement;

import com.saburi.root.repositories.PagingAndSortingRepo;
import com.saburi.customer.engagement.dtos.EngagementMini;
import java.util.List;


public interface EngagementRepo  extends PagingAndSortingRepo<Engagement, Long>{



public List<EngagementMini> findAllBy();


}
