/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.banking.banktransfer;

import com.saburi.banking.banktransfer.dtos.BankTransferRequest;
import com.saburi.root.controllers.BaseController;
import com.saburi.root.services.BaseService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
@RequestMapping("banktransfers")
public class BankTransferController  extends BaseController<BankTransfer, BankTransferRequest, Integer>{




@Autowired
    private BankTransferService bankTransferService;@Override
    protected BaseService<BankTransfer, BankTransferRequest, Integer> getBaseService() {
        return bankTransferService;
    }

}
