/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.banking.banktransfer;

import com.saburi.root.repositories.PagingAndSortingRepo;
import com.saburi.banking.banktransfer.dtos.BankTransferMini;
import java.util.List;


public interface BankTransferRepo  extends PagingAndSortingRepo<BankTransfer, Integer>{



public List<BankTransferMini> findAllBy();


}
