/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.loan.profile.dtos;

import jakarta.validation.constraints.NotNull;
import org.springframework.web.multipart.MultipartFile;
import jakarta.validation.constraints.Size;
import com.saburi.root.enums.Gender;
import com.saburi.root.enums.WorkTypes;


public class ProfileRequest{

@NotNull(message =  "The field: Photo cannot be null")
private byte[] photo;
@Size(max =  20, message =  "The field: First Name size cannot be greater than 20")
@NotNull(message =  "The field: First Name cannot be null")
private String firstName;
@Size(max =  20, message =  "The field: Last Name size cannot be greater than 20")
@NotNull(message =  "The field: Last Name cannot be null")
private String lastName;
@Size(max =  20, message =  "The field: Other Names size cannot be greater than 20")
private String otherNames;
private Gender gender;
private String maritalStatusId;
private String countryId;
@Size(max =  100, message =  "The field: Spouse Name size cannot be greater than 100")
private String spouseName;
@Size(max =  100, message =  "The field: Spouse Contact size cannot be greater than 100")
private String spouseContact;
@Size(max =  100, message =  "The field: NO Kin size cannot be greater than 100")
private String nOKin;
@Size(max =  100, message =  "The field: NO Kin Contact size cannot be greater than 100")
private String nOKinContact;
private String idTypeId;
@Size(max =  100, message =  "The field: Id No size cannot be greater than 100")
private String idNo;
@Size(max =  30, message =  "The field: Primary Phone No size cannot be greater than 30")
private String primaryPhoneNo;
@Size(max =  30, message =  "The field: Other Phone Nos size cannot be greater than 30")
private String otherPhoneNos;
private byte[] fingerPrint;
@Size(max =  100, message =  "The field: Email size cannot be greater than 100")
private String email;
@Size(max =  200, message =  "The field: Home Address size cannot be greater than 200")
private String homeAddress;
@Size(max =  200, message =  "The field: Residential Address size cannot be greater than 200")
private String residentialAddress;
@Size(max =  200, message =  "The field: Residence Coordinates size cannot be greater than 200")
private String residenceCoordinates;
@Size(max =  200, message =  "The field: Address Details size cannot be greater than 200")
private String addressDetails;
private String occupationId;
private WorkTypes workType;
private String businessCategoryId;
@Size(max =  200, message =  "The field: Business Description size cannot be greater than 200")
private String businessDescriptions;
@Size(max =  100, message =  "The field: Designation size cannot be greater than 100")
private String designation;
@Size(max =  100, message =  "The field: Business Name size cannot be greater than 100")
private String businessName;
@Size(max =  100, message =  "The field: Business Location size cannot be greater than 100")
private String businessLocation;
@Size(max =  100, message =  "The field: Work Coordinates size cannot be greater than 100")
private String workCoordinates;
private boolean idNoVerified;
private boolean phoneVerified;

public ProfileRequest(){
}
public  ProfileRequest(MultipartFile photo,String firstName,String lastName,String otherNames,Gender gender,String maritalStatusId,String countryId,String spouseName,String spouseContact,String nOKin,String nOKinContact,String idTypeId,String idNo,String primaryPhoneNo,String otherPhoneNos,MultipartFile fingerPrint,String email,String homeAddress,String residentialAddress,String residenceCoordinates,String addressDetails,String occupationId,WorkTypes workType,String businessCategoryId,String businessDescriptions,String designation,String businessName,String businessLocation,String workCoordinates,boolean idNoVerified,boolean phoneVerified){
 this.photo = photo;
this.firstName = firstName;
this.lastName = lastName;
this.otherNames = otherNames;
this.gender = gender;
this.maritalStatusId = maritalStatusId;
this.countryId = countryId;
this.spouseName = spouseName;
this.spouseContact = spouseContact;
this.nOKin = nOKin;
this.nOKinContact = nOKinContact;
this.idTypeId = idTypeId;
this.idNo = idNo;
this.primaryPhoneNo = primaryPhoneNo;
this.otherPhoneNos = otherPhoneNos;
this.fingerPrint = fingerPrint;
this.email = email;
this.homeAddress = homeAddress;
this.residentialAddress = residentialAddress;
this.residenceCoordinates = residenceCoordinates;
this.addressDetails = addressDetails;
this.occupationId = occupationId;
this.workType = workType;
this.businessCategoryId = businessCategoryId;
this.businessDescriptions = businessDescriptions;
this.designation = designation;
this.businessName = businessName;
this.businessLocation = businessLocation;
this.workCoordinates = workCoordinates;
this.idNoVerified = idNoVerified;
this.phoneVerified = phoneVerified;

}

public MultipartFile getPhoto(){
 return photo;
}
public void setPhoto(MultipartFile photo){
this.photo = photo;
}public String getFirstName(){
 return firstName;
}
public void setFirstName(String firstName){
this.firstName = firstName;
}public String getLastName(){
 return lastName;
}
public void setLastName(String lastName){
this.lastName = lastName;
}public String getOtherNames(){
 return otherNames;
}
public void setOtherNames(String otherNames){
this.otherNames = otherNames;
}public Gender getGender(){
 return gender;
}
public void setGender(Gender gender){
this.gender = gender;
}public String getMaritalStatusId(){
 return maritalStatusId;
}
public void setMaritalStatusId(String maritalStatusId){
this.maritalStatusId = maritalStatusId;
}public String getCountryId(){
 return countryId;
}
public void setCountryId(String countryId){
this.countryId = countryId;
}public String getSpouseName(){
 return spouseName;
}
public void setSpouseName(String spouseName){
this.spouseName = spouseName;
}public String getSpouseContact(){
 return spouseContact;
}
public void setSpouseContact(String spouseContact){
this.spouseContact = spouseContact;
}public String getNOKin(){
 return nOKin;
}
public void setNOKin(String nOKin){
this.nOKin = nOKin;
}public String getNOKinContact(){
 return nOKinContact;
}
public void setNOKinContact(String nOKinContact){
this.nOKinContact = nOKinContact;
}public String getIdTypeId(){
 return idTypeId;
}
public void setIdTypeId(String idTypeId){
this.idTypeId = idTypeId;
}public String getIdNo(){
 return idNo;
}
public void setIdNo(String idNo){
this.idNo = idNo;
}public String getPrimaryPhoneNo(){
 return primaryPhoneNo;
}
public void setPrimaryPhoneNo(String primaryPhoneNo){
this.primaryPhoneNo = primaryPhoneNo;
}public String getOtherPhoneNos(){
 return otherPhoneNos;
}
public void setOtherPhoneNos(String otherPhoneNos){
this.otherPhoneNos = otherPhoneNos;
}public MultipartFile getFingerPrint(){
 return fingerPrint;
}
public void setFingerPrint(MultipartFile fingerPrint){
this.fingerPrint = fingerPrint;
}public String getEmail(){
 return email;
}
public void setEmail(String email){
this.email = email;
}public String getHomeAddress(){
 return homeAddress;
}
public void setHomeAddress(String homeAddress){
this.homeAddress = homeAddress;
}public String getResidentialAddress(){
 return residentialAddress;
}
public void setResidentialAddress(String residentialAddress){
this.residentialAddress = residentialAddress;
}public String getResidenceCoordinates(){
 return residenceCoordinates;
}
public void setResidenceCoordinates(String residenceCoordinates){
this.residenceCoordinates = residenceCoordinates;
}public String getAddressDetails(){
 return addressDetails;
}
public void setAddressDetails(String addressDetails){
this.addressDetails = addressDetails;
}public String getOccupationId(){
 return occupationId;
}
public void setOccupationId(String occupationId){
this.occupationId = occupationId;
}public WorkTypes getWorkType(){
 return workType;
}
public void setWorkType(WorkTypes workType){
this.workType = workType;
}public String getBusinessCategoryId(){
 return businessCategoryId;
}
public void setBusinessCategoryId(String businessCategoryId){
this.businessCategoryId = businessCategoryId;
}public String getBusinessDescriptions(){
 return businessDescriptions;
}
public void setBusinessDescriptions(String businessDescriptions){
this.businessDescriptions = businessDescriptions;
}public String getDesignation(){
 return designation;
}
public void setDesignation(String designation){
this.designation = designation;
}public String getBusinessName(){
 return businessName;
}
public void setBusinessName(String businessName){
this.businessName = businessName;
}public String getBusinessLocation(){
 return businessLocation;
}
public void setBusinessLocation(String businessLocation){
this.businessLocation = businessLocation;
}public String getWorkCoordinates(){
 return workCoordinates;
}
public void setWorkCoordinates(String workCoordinates){
this.workCoordinates = workCoordinates;
}public boolean isIdNoVerified(){
 return idNoVerified;
}
public void setIdNoVerified(boolean idNoVerified){
this.idNoVerified = idNoVerified;
}public boolean isPhoneVerified(){
 return phoneVerified;
}
public void setPhoneVerified(boolean phoneVerified){
this.phoneVerified = phoneVerified;
}


}
