/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.organisation.company;

import com.saburi.root.repositories.PagingAndSortingRepo;
import com.saburi.organisation.company.dtos.CompanyMini;
import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.Query;


public interface CompanyRepo  extends PagingAndSortingRepo<Company, String>{



 @Query("SELECT MAX(idHelper) from Company c ")
public Optional<Integer> getMaxIdHelper();


public List<CompanyMini> findByCompanyName(String companyName);

public List<CompanyMini> findAllBy();


}
