/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.organisation.company;

import com.saburi.organisation.company.dtos.CompanyRequest;
import com.saburi.root.controllers.FormDataController;
import com.saburi.root.services.BaseServiceIDGen;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
@RequestMapping("companies")
public class CompanyController  extends FormDataController<Company, CompanyRequest, String>{




@Autowired
    private CompanyService companyService;@Override
    protected BaseServiceIDGen<Company, CompanyRequest, String> getBaseService() {
        return companyService;
    }

}
