/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.organisation.company;

import com.saburi.root.repositories.PagingAndSortingRepo;
import com.saburi.organisation.company.dtos.CompanyRequest;
import org.springframework.beans.factory.annotation.Autowired;import org.springframework.stereotype.Service;
import com.saburi.root.services.BaseServiceIDGen;
import com.saburi.root.dtos.ResponseData;
import com.saburi.root.utils.KnownException;
import java.util.List;import java.util.Objects;


@Service
public class CompanyService  extends BaseServiceIDGen<Company,CompanyRequest, String>{




private static final int RESOURCE_ID = 1;
    private static final String ENTITY_CAPTION = "Company";
    @Autowired
    private CompanyRepo companyRepo;
@Override
public String getEntityCaption(){
 return ENTITY_CAPTION;
}
@Override
public PagingAndSortingRepo<Company, String> getRepository(){
 return companyRepo;
}
@Override
public List<? extends ResponseData> getMiniData(){
 return companyRepo.findAllBy();
}
@Override
public int getResourceID(){
 return RESOURCE_ID;
}
@Override
    protected int getNextIdHelper(Object object) {
        return companyRepo.getMaxIdHelper().orElse(0) + 1;
    }
 @Override
    protected Company modifyToSave(Company company) throws  Exception {
       
        if (company.getId() == null) {
            company.setIdHelper(this.getNextIdHelper(company));
            company.setId(this.getNextID(company));
        }
        return company;
    }@Override
public boolean isValid(Company company)throws Exception{
 if (companyRepo.findByCompanyName(company. getCompanyName())
                .stream().filter(c -> !Objects.equals(c.getId(), company.getId())).count() > 0) {
            throw new KnownException("A record with name: " + company. getCompanyName()+ " already exists");
        }return super.isValid(company);
}
@Override
public Company instantiate(){
 return new Company();
}
@Override
    public Company setEntity(Company e, CompanyRequest req) throws Exception{
e.setLogo(req. getLogo().getBytes());
e.setCompanyName(req. getCompanyName());
e.setBusinessType(req. getBusinessType());
e.setAddress(req. getAddress());
e.setPhoneNo(req. getPhoneNo());
e.setEmail(req. getEmail());
e.setWebsite(req. getWebsite());
e.setTagLine(req. getTagLine());
e.setDevName(req. getDevName());
e.setDbType(req. getDbType());
e.setDbUsername(req. getDbUsername());
e.setDbPassword(req. getDbPassword());
e.setDbPort(req. getDbPort());
e.setDbHost(req. getDbHost());
e.setUrl(req. getUrl());
return e;

}


}
