/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.customer.engagement.dtos;

import com.saburi.root.dtos.ResponseData;
import com.saburi.customer.customer.Customer;


public interface EngagementMini  extends ResponseData{


Long getId();
Customer getCustomer();


}
