/*
 Sam Buriima
generated by Saburi Tools
*/
package com.saburi.customer.engagement.dtos;

import com.saburi.customer.customer.Customer;
import java.time.LocalDate;
import com.saburi.customer.enums.EngagementReasons;
import com.saburi.customer.enums.EngagementModes;
import javax.validation.constraints.Size;
import com.saburi.customer.engagementmodes.EngagementModes;
import com.saburi.customer.engagement.Engagement;


public class EngagementRequest{

private Customer customer;
private LocalDate engagementDate;
private EngagementReasons engagementReason;
private EngagementModes engagementMode;
@Size(max =  100, message =  "The field: Description size cannot be greater than 100")
private String description;
@Size(max =  100, message =  "The field: Attending Personnel size cannot be greater than 100")
private String attendingPersonnel;
private String status;
private  nextEngagementDate;
private EngagementModes expectedNextEngagementMode;
private Engagement parentEngagement;

public EngagementRequest(){
}
public  EngagementRequest(Customer customer,LocalDate engagementDate,EngagementReasons engagementReason,EngagementModes engagementMode,String description,String attendingPersonnel,String status, nextEngagementDate,EngagementModes expectedNextEngagementMode,Engagement parentEngagement){
 this.customer = customer;
this.engagementDate = engagementDate;
this.engagementReason = engagementReason;
this.engagementMode = engagementMode;
this.description = description;
this.attendingPersonnel = attendingPersonnel;
this.status = status;
this.nextEngagementDate = nextEngagementDate;
this.expectedNextEngagementMode = expectedNextEngagementMode;
this.parentEngagement = parentEngagement;

}

public Customer getCustomer(){
 return customer;
}
public void setCustomer(Customer customer){
this.customer = customer;
}public LocalDate getEngagementDate(){
 return engagementDate;
}
public void setEngagementDate(LocalDate engagementDate){
this.engagementDate = engagementDate;
}public EngagementReasons getEngagementReason(){
 return engagementReason;
}
public void setEngagementReason(EngagementReasons engagementReason){
this.engagementReason = engagementReason;
}public EngagementModes getEngagementMode(){
 return engagementMode;
}
public void setEngagementMode(EngagementModes engagementMode){
this.engagementMode = engagementMode;
}public String getDescription(){
 return description;
}
public void setDescription(String description){
this.description = description;
}public String getAttendingPersonnel(){
 return attendingPersonnel;
}
public void setAttendingPersonnel(String attendingPersonnel){
this.attendingPersonnel = attendingPersonnel;
}public String getStatus(){
 return status;
}
public void setStatus(String status){
this.status = status;
}public  getNextEngagementDate(){
 return nextEngagementDate;
}
public void setNextEngagementDate( nextEngagementDate){
this.nextEngagementDate = nextEngagementDate;
}public EngagementModes getExpectedNextEngagementMode(){
 return expectedNextEngagementMode;
}
public void setExpectedNextEngagementMode(EngagementModes expectedNextEngagementMode){
this.expectedNextEngagementMode = expectedNextEngagementMode;
}public Engagement getParentEngagement(){
 return parentEngagement;
}
public void setParentEngagement(Engagement parentEngagement){
this.parentEngagement = parentEngagement;
}


}
