## YAML Template.
---
services:
    springconfig:
        image: docker.io/saburi/spring-config:latest
        ports:
            8888:8888
        environment:
            -"SPRING_PROFILES_ACTIVE"=prod"
    networks:
        backend:
            aliases:
                - "springconfig"
networks:
    backend:
        driver: bridge        
    
            